openapi: 3.0.2
info:
  title: OGCAPI
  version: 0.0.1
  description: Implemations of OGC API
  license:
    name: OGC license
    url: http://www.ogc.org/legal/
  contact:
    email: kortxyz@gmail.com
tags:
  - name: Processes
    description: Processes from the API
servers:
  - url: https://localhost
paths:
  /processes:
    get:
      summary: retrieve the list of available processes
      description: >
        The list of processes contains a summary of each process the OGC API -
        Processes offers, including the link to a more detailed description of
        the process.


        For more information, see [Section
        7.9](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_process_list).
      operationId: getProcesses
      tags:
        - Processes
      responses:
        '200':
          description: ProcessList
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '404':
          description: The requested URI was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
  /processes/{processID}:
    get:
      summary: retrieve a process description
      description: >
        The process description contains information about inputs and outputs
        and a link to the execution-endpoint for the process. The Core does not
        mandate the use of a specific process description to specify the
        interface of a process. That said, the Core requirements class makes the
        following recommendation:


        Implementations SHOULD consider supporting the OGC process description.


        For more information, see [Section
        7.10](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_process_description).
      operationId: getProcessDescription
      tags:
        - Processes
      parameters:
        - $ref: '#/components/parameters/processID'
      responses:
        '200':
          description: ProcessDescription
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
  /jobs:
    get:
      summary: retrieve the list of jobs.
      description: >
        Lists available jobs.


        For more information, see [Section
        11](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_job_list).
      operationId: getJobs
      tags:
        - Processes
      responses:
        '200':
          description: JobList
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
  /processes/{processID}/execution:
    post:
      summary: execute a process.
      description: >
        Create a new job.


        For more information, see [Section
        7.11](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_create_job).
      operationId: executeJob
      tags:
        - Processes
      parameters:
        - $ref: '#/components/parameters/processID'
      requestBody:
        description: Mandatory execute request JSON
        required: true
        content:
          application/json:
            schema:
              description: Execute
              type: object
              additionalProperties: true
      responses:
        '200':
          description: ExecuteSync
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '201':
          description: ExecuteAsync
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
  /jobs/{jobId}:
    get:
      summary: retrieve the status of a job
      description: |
        Shows the status of a job.

         For more information, see [Section 7.12](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_retrieve_status_info).
      operationId: getJobStatus
      tags:
        - Processes
      parameters:
        - $ref: '#/components/parameters/jobId'
      responses:
        '200':
          description: Status
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
    delete:
      summary: cancel a job execution, remove a finished job
      description: >
        Cancel a job execution and remove it from the jobs list.


        For more information, see [Section
        13](https://docs.ogc.org/is/18-062r2/18-062r2.html#Dismiss).
      operationId: deleteJob
      tags:
        - Processes
      parameters:
        - $ref: '#/components/parameters/jobId'
      responses:
        '200':
          description: Status
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
  /jobs/{jobId}/results:
    get:
      summary: retrieve the result(s) of a job
      description: >
        Lists available results of a job. In case of a failure, lists exceptions
        instead.


        For more information, see [Section
        7.13](https://docs.ogc.org/is/18-062r2/18-062r2.html#sc_retrieve_job_results).
      operationId: getJobResults
      tags:
        - Processes
      parameters:
        - $ref: '#/components/parameters/jobId'
      responses:
        '200':
          description: Results
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
components:
  schemas:
    exception:
      type: object
      description: >-
        Information about the exception: an error code plus an optional
        description.
      required:
        - statusCode
      properties:
        statusCode:
          type: integer
        error:
          type: string
        message:
          type: string
      example:
        statusCode: 404
        error: Not Found
        message: Route GET:/tileMatrixSets not found
  parameters:
    processID:
      name: processID
      in: path
      required: true
      schema:
        type: string
    jobId:
      name: jobId
      in: path
      description: local identifier of a job
      required: true
      schema:
        type: string
